apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus
    isDefault: true
    editable: true
    jsonData:
      # When a metric data point has an exemplar (trace ID written by Tempo's
      # metrics generator), clicking it navigates to that trace in Tempo.
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
